export Artifact from './artifact'
export PropertyParty from './propertyParty'
export PropertySpatialUnit from './propertySpatialUnit'
export PropertyTenure from './propertyTenure'
export ResearchTomogram from './researchTomogram'