import { ECPair } from 'bitcoinjs-lib'
import { floTestnet } from '../src/config'
import { Artifact } from '../src/modules/records/artifact'

// Small Artifact (fits into one FLO tx)
// Step 1 - Create
let artifactSmall = new Artifact()
artifactSmall.setTitle('Test Artifact')
artifactSmall.setDescription('Super Duper')

// Step 2 - Sign
let network = floTestnet.network
const wif = 'cRVa9rNx5N1YKBw8PhavegJPFCiYCfC4n8cYmdc3X1Y6TyFZGG4B'
const myECPair = ECPair.fromWIF(wif, network)
// const p2pkh = bitcoin.payments.p2pkh({pubkey: myECPair.publicKey, network}).address
// let pubAddress = "ofbB67gqjgaYi45u8Qk2U3hGoCmyZcgbN4"
artifactSmall.signSelf(myECPair)
// console.log(artifactSmall.serialize('publish'))
// console.log('has valid signature: ', artifactSmall.hasValidSignature())

// --------------------------------------------------------------------
// Large Artifact (gets split up into multiparts)
let artifactLarge = new Artifact()
artifactLarge.setTitle('Test Artifact')
artifactLarge.setDescription('MultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLarge')

// Step 2 - Sign
artifactLarge.signSelf(myECPair)
// console.log(artifactLarge.serialize('publish'))
// console.log(artifactLarge.serialize('publish').length)
// console.log('has valid signature: ', artifactLarge.hasValidSignature())

// Step 3 - Publish
export {
  artifactSmall,
  artifactLarge
}
