import bitcoin from "bitcoinjs-lib";
import {verify} from "bitcoinjs-message";
import {flo_testnet} from '../src/config'
import {Artifact} from '../src/modules/records/artifact'

// Small Artifact (fits into one FLO tx)
//Step 1 - Create
let artifactSmall = new Artifact()
artifactSmall.setTitle('Test Artifact')
artifactSmall.setDescription('Super Duper')


//Step 2 - Sign
let network = flo_testnet.network
const wif = 'cRVa9rNx5N1YKBw8PhavegJPFCiYCfC4n8cYmdc3X1Y6TyFZGG4B'
const ECPair = bitcoin.ECPair.fromWIF(wif, network)
// const p2pkh = bitcoin.payments.p2pkh({pubkey: ECPair.publicKey, network}).address
// let pubAddress = "ofbB67gqjgaYi45u8Qk2U3hGoCmyZcgbN4"
artifactSmall.signSelf(ECPair)
// console.log(artifactSmall.serialize('publish'))
// console.log('has valid signature: ', artifactSmall.hasValidSignature())

// --------------------------------------------------------------------
// Large Artifact (gets split up into multiparts)
let artifactLarge = new Artifact()
artifactLarge.setTitle('Test Artifact')
artifactLarge.setDescription('MultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartMultipartartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLargeartifactLarge')


//Step 2 - Sign
artifactLarge.signSelf(ECPair)
// console.log(artifactLarge.serialize('publish'))
// console.log(artifactLarge.serialize('publish').length)
// console.log('has valid signature: ', artifactLarge.hasValidSignature())


//Step 3 - Publish
export {
	artifactSmall,
	artifactLarge
}